language: cpp

compiler:
  - clang
  - gcc

script:
  - make
  - make test

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - libboost-all-dev
      - gcc-5
      - g++-5
      - clang-3.6
