language: cpp

compiler:
  - clang
  - gcc

script:
  - make
  - make test

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
    packages:
      - libboost-all-dev
      - gcc-4.9
      - g++-4.9
      - clang-3.5
