language: cpp
sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

compiler:
  - gcc

script:
  - make test CXX=g++-4.9 CC=gcc-4.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - g++-4.9
      - libboost1.55-all-dev
