language: cpp
sudo: false

compiler:
  - gcc

env: GCC_VERSION=4.9.0 BOOST_VERSION=1.58.0

script:
  - echo $CC
  - echo $CXX
  - echo $GCC_VERSION
  - echo $BOOST_ROOT
  - make CC=$CC CXX=$CXX
  - make test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

after_install:
  - wget https://raw.githubusercontent.com/cbeck88/travis-cpp-assistant/master/install.sh
  - chmod +x install.sh
  - source ./install.sh
