language: cpp
dist: precise
sudo: false

compiler:
  - gcc

script:
  - make CC=g++-4.9 CXX=g++-4.9
  - make test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
