language: cpp
sudo: required

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

compiler:
  - gcc

env: GCC_VERSION=5.3.0 BOOST_VERSION=1.58.0

script:
  - echo $CC
  - echo $CXX
  - echo $BOOST_ROOT
  - make CC=g++-5.3 CXX=g++-5.3
  - make test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

install:
  - wget https://raw.githubusercontent.com/cbeck88/travis-cpp-assistant/master/install.sh
  - chmod +x install.sh
  - source ./install.sh
