language: cpp
dist: precise
sudo: false

compiler:
  - gcc
#  - clang

script:
  - make CC=g++-4.9 CXX=g++-4.9
  - make test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
#      - llvm-toolchain-precise-3.6
    packages:
      - libboost-all-dev
      - g++-4.9
#      - clang-3.6
