language: cpp
dist: precise
sudo: required

compiler:
  - gcc
#  - clang

script:
  - make CC=g++-4.9 CXX=g++-4.9
  - make test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
#      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.9
#      - libboost-all-dev
#      - clang-3.6

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-all-dev-1.55
